import { prisma } from '../config/database';
import { redisConnection } from '../config/redis';
import { checkElasticsearch } from '../config/elasticsearch';
import { addEmailJob, getQueueStats } from '../queue/email.queue';
import { processEmailJob } from '../queue/email.worker';
import { rateLimitService } from '../services/rateLimit.service';
import { searchService } from '../services/search.service';
import { schedulerService } from '../services/scheduler.service';
import { logger } from '../utils/logger';
import { Job } from 'bullmq';
import { SendEmailJobData, SendEmailJobResult } from '../types/queue.types';
import { EmailStatus } from '@prisma/client';

interface TestSummary {
  name: string;
  passed: boolean;
  durationMs: number;
  details?: string;
}

const results: TestSummary[] = [];

async function runTest(name: string, fn: () => Promise<void>) {
  logger.info(`\n==================================================\n🧪 STARTING: ${name}\n==================================================`);
  const start = Date.now();
  try {
    await fn();
    const durationMs = Date.now() - start;
    results.push({ name, passed: true, durationMs });
    logger.info(`✅ PASSED: ${name} (${durationMs}ms)`);
  } catch (error) {
    const durationMs = Date.now() - start;
    const details = error instanceof Error ? error.message : String(error);
    results.push({ name, passed: false, durationMs, details });
    logger.error({ error }, `❌ FAILED: ${name}`);
  }
}

async function main() {
  logger.info('🚀 Starting Master Automated Test Suite for AutoMail Scheduler...\n');

  // Test 1: Infrastructure Connectivity
  await runTest('1. Infrastructure Connectivity (Postgres, Redis, Elasticsearch)', async () => {
    await prisma.$queryRaw`SELECT 1`;
    const ping = await redisConnection.ping();
    if (ping !== 'PONG') throw new Error('Redis ping failed');
    const esOk = await checkElasticsearch();
    if (!esOk) throw new Error('Elasticsearch cluster unreachable');
  });

  // Test 2: Zero-Cron BullMQ Delayed Scheduling
  await runTest('2. Zero-Cron BullMQ Delayed Job Dispatch', async () => {
    const delayMs = 1500;
    const testJob = await addEmailJob(
      {
        emailId: `test_delayed_${Date.now()}`,
        campaignId: 'test_camp_e2e',
        senderId: 'test_sender_e2e',
        recipient: 'test.e2e@example.com',
        subject: 'Master Test Delayed Email',
        body: 'Testing BullMQ delay timer',
        scheduledAt: new Date(Date.now() + delayMs).toISOString(),
      },
      delayMs
    );

    if (!testJob.id) throw new Error('Job ID was not generated by BullMQ');
    const stats = await getQueueStats();
    if (stats.delayed < 1 && stats.waiting < 1 && stats.completed < 1) {
      throw new Error('Delayed job not found in BullMQ stats');
    }
  });

  // Test 3: Minimum Inter-Send Delay Throttling
  await runTest('3. Redis-Backed Minimum Inter-Email Delay Throttling', async () => {
    const senderId = `test_throttle_${Date.now()}`;
    const minDelayMs = 1000;

    await rateLimitService.enforceMinimumDelay(senderId, minDelayMs);
    const tStart = Date.now();
    await rateLimitService.enforceMinimumDelay(senderId, minDelayMs);
    const elapsed = Date.now() - tStart;

    if (elapsed < 900) {
      throw new Error(`Minimum delay was not enforced. Expected >= 1000ms, got ${elapsed}ms`);
    }
  });

  // Test 4: Redis Atomic Hourly Rate Limiting & Automatic Rescheduling
  await runTest('4. Distributed Hourly Rate Limiting & Auto-Rescheduling', async () => {
    const senderId = `test_rate_limiter_${Date.now()}`;
    const limit = 2;

    const check1 = await rateLimitService.checkAndIncrementHourlyLimit(senderId, limit);
    if (!check1.allowed || check1.currentCount !== 1) throw new Error('Check 1 failed');

    const check2 = await rateLimitService.checkAndIncrementHourlyLimit(senderId, limit);
    if (!check2.allowed || check2.currentCount !== 2) throw new Error('Check 2 failed');

    const check3 = await rateLimitService.checkAndIncrementHourlyLimit(senderId, limit);
    if (check3.allowed) throw new Error('Check 3 should have been BLOCKED by rate limiter');
    if (check3.nextWindowMs <= 0) throw new Error('Next window calculation invalid');
  });

  // Test 5: Atomic Compare-And-Swap Idempotency Protection
  await runTest('5. Database Atomic CAS Lock & Idempotency Duplicate Prevention', async () => {
    const user = await prisma.user.findFirst();
    if (!user) throw new Error('No test user in database');

    const sender = await prisma.sender.findFirst({ where: { userId: user.id } });
    if (!sender) throw new Error('No test sender in database');

    const campaign = await prisma.campaign.create({
      data: {
        userId: user.id,
        subject: 'Idempotency Test Campaign',
        body: 'Idempotency body',
        startTime: new Date(),
      },
    });

    const email = await prisma.email.create({
      data: {
        campaignId: campaign.id,
        senderId: sender.id,
        recipient: 'idempotency.check@example.com',
        subject: 'Idempotency Subject',
        body: 'Body text',
        scheduledAt: new Date(),
        status: EmailStatus.sent, // Marked as SENT
        sentAt: new Date(),
      },
    });

    const mockJob = {
      id: `job_dup_${email.id}`,
      data: {
        emailId: email.id,
        campaignId: campaign.id,
        senderId: sender.id,
        recipient: email.recipient,
        subject: email.subject,
        body: email.body,
        scheduledAt: email.scheduledAt.toISOString(),
      },
      attemptsMade: 0,
    } as unknown as Job<SendEmailJobData, SendEmailJobResult>;

    const result = await processEmailJob(mockJob);
    if (result.messageId !== 'already_sent_idempotent_skip') {
      throw new Error(`Expected already_sent_idempotent_skip, got: ${result.messageId}`);
    }
  });

  // Test 6: Elasticsearch Multi-Match Search
  await runTest('6. Elasticsearch Multi-Match Indexing & Query Retrieval', async () => {
    await searchService.ensureIndexExists();
    const testId = `es_test_${Date.now()}`;

    await searchService.indexEmail({
      id: testId,
      campaignId: 'camp_es_test',
      senderId: 'sender_es_test',
      recipient: 'cybernetic.search.target@domain.org',
      subject: 'Unique Quantum Encryption Protocol',
      body: 'Body containing keyword superluminal-transmission',
      status: 'sent',
      scheduledAt: new Date().toISOString(),
      createdAt: new Date().toISOString(),
    });

    // Wait a brief moment for ES refresh
    await new Promise((r) => setTimeout(r, 1000));

    const searchResult = await searchService.searchEmails('superluminal-transmission');
    if (!searchResult || searchResult.emails.length === 0) {
      throw new Error('Elasticsearch did not return indexed document');
    }

    const match = searchResult.emails.find((e) => e.id === testId);
    if (!match) throw new Error('Indexed document ID not found in search results');
  });

  // Print Summary Table
  logger.info('\n==================================================');
  logger.info('📊 MASTER TEST SUITE RESULTS SUMMARY');
  logger.info('==================================================');

  let allPassed = true;
  for (const r of results) {
    const icon = r.passed ? '✅ PASS' : '❌ FAIL';
    logger.info(`${icon} | ${r.name.padEnd(65)} | ${r.durationMs}ms`);
    if (!r.passed) allPassed = false;
  }

  logger.info('==================================================\n');

  if (allPassed) {
    logger.info('🎉 ALL 6 COMPREHENSIVE TESTS PASSED SUCCESSFULLY!\n');
    process.exit(0);
  } else {
    logger.error('⚠️ SOME TESTS FAILED.');
    process.exit(1);
  }
}

main().catch((err) => {
  logger.error({ err }, 'Master test execution failed');
  process.exit(1);
});
